### ISSUE TITLE
Ctrl + Shift + I to remove unused imports 

### ISSUE THREAD

**Issue by aceonline666** [Grogdunn/vscode-nb-keybinding#2]
Could you include the Netbeans shortcut ctrl + shift + i to remove unused imports from the current file? I use that shortcut a lot in Netbeans and it would be nice if I wouldn't have to configure it manually in VSCode.

**Comment by Grogdunn** [comment]
pull request are welcome :smile: 

At the moment I've only setting some already present shortcut. Removed imports are Java-specific and VSCode doesn't have a keybinding for this (I think).

**Comment by Grogdunn** [comment]
Issue clean up... no feedback given
