### ISSUE TITLE
Ctrl + o to open classes, Alt + shift + o to open files and Ctrl + shift + o to open files

### ISSUE THREAD

**Issue by jabdoa2** [Grogdunn/vscode-nb-keybinding#3]
Currently ctrl + o will open new files. That should become Ctrl + shift + o
Ctrl + o -> open classes
Alt + shift + o -> Open file by name

**Comment by Grogdunn** [comment]
Can you send me a pull request?

**Comment by Grogdunn** [comment]
Issue clean up... no feedback given (or maybe it is not possible to do that)

**Comment by jabdoa2** [comment]
Did not create a PR yet. Issue is still valid in my opinion. This is a clear bug.

**Comment by Grogdunn** [comment]
Well I haven't find any option to "limit" the ability to open only the *.java file with CTRL+O (or better *.java file in project and *.class + source in dependecy jars).
Rebind open file to CTRL+SHIFT+O instead is pretty easy... but without other shortcut doesn't lead any value in my opinion.
