### ISSUE TITLE
Not working on VS 1.73.1

### ISSUE THREAD

**Issue by TheJenos** [Grogdunn/vscode-nb-keybinding#8]
![image](https://user-images.githubusercontent.com/13817642/205135121-14de6828-e45a-4142-b60b-42cd8ab074e8.png)

**Comment by Grogdunn** [comment]
More information needed. Same version (tested on Manjaro and Windows) and all tested binding works.

**Comment by TheJenos** [comment]
Did you test on a fresh install? Because I moved ubuntu into elementary after that this happened. 😢 I checked the settings nothing is wrong there. In my college live I used to work with Netbeans and I still got some keybind habits. I really wanna to fix this 😢

**Comment by Grogdunn** [comment]
A fresh install only under Manjaro, maybe you have another plugin that oveerride some keybinding?

**Comment by Grogdunn** [comment]
Close issue 👍
